#macro PLAYER_ORIGIN_OFFSET (16)

#macro PLAYER_HEALTH_MINIMUM (0)
#macro PLAYER_HEALTH_MAXIMUM (100)
#macro PLAYER_HEALTH_DEFAULT (PLAYER_HEALTH_MAXIMUM)

#macro PLAYER_STAMINA_MINIMUM   (0)
#macro PLAYER_STAMINA_MAXIMUM   (100)
#macro PLAYER_STAMINA_DEFAULT   (PLAYER_STAMINA_MAXIMUM)

#macro PLAYER_IDLE_STAMINA_GAIN_PER_FRAME      (0.75)
#macro PLAYER_WALK_STAMINA_GAIN_PER_FRAME      (0.5)
#macro PLAYER_RUN_STAMINA_COST_PER_FRAME       (0.5)
#macro PLAYER_DODGE_STAMINA_COST               (PLAYER_STAMINA_MAXIMUM * 0.35)
#macro PLAYER_EXHAUSTED_STAMINA_GAIN_PER_FRAME (0.25)

#macro PLAYER_IDLE_SPEED      (0)
#macro PLAYER_WALK_SPEED      (2)
#macro PLAYER_RUN_SPEED       (4)
#macro PLAYER_DODGE_SPEED     (8)
#macro PLAYER_EXHAUSTED_SPEED (1)

#macro PLAYER_DODGE_LENGTH_FRAMES         (8)
#macro PLAYER_EXHAUSTED_STAMINA_THRESHOLD (PLAYER_STAMINA_MAXIMUM * 0.3)